import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
          position="top-right"
          reverseOrder={false}
          gutter={8}
          toastOptions={{
            duration: 2800,
            className:
              "bg-neutral-900 text-white border border-neutral-800 rounded-xl px-4 py-3 shadow-xl",
            success: {
              icon: "✨",
              className:
                "bg-neutral-900 text-green-400 border border-neutral-800 px-4 py-3 rounded-xl",
            },
            error: {
              icon: "❌",
              className:
                "bg-neutral-900 text-red-400 border border-neutral-800 px-4 py-3 rounded-xl",
            },
          }}
        />
      </body>
    </html>
  );
}
